services:
  - type: web
    name: padua
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    disk:
      name: n8n-data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: PORT
        value: "5678"
      - key: N8N_PORT
        value: "5678"
      - key: WEBHOOK_URL
        value: https://padua.onrender.com/
      - key: N8N_HOST
        value: padua.onrender.com
      - key: N8N_PROTOCOL
        value: https
      - key: N8N_EDITOR_BASE_URL
        value: https://padua.onrender.com
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        sync: false
      - key: DB_SQLITE_POOL_SIZE
        value: "2"
      - key: N8N_RUNNERS_ENABLED
        value: "true"
      - key: N8N_BLOCK_ENV_ACCESS_IN_NODE
        value: "false"
      - key: N8N_GIT_NODE_DISABLE_BARE_REPOS
        value: "true"
